version: "3.6"

services:
  
  balugumi_prod:
    build: "."
    container_name: balugumi_prod
    network_mode: host
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - /balugumi.com_docker:/usr/local/apache2/htdocs
      
